### ISSUE TITLE
OnChange event fail

### ISSUE THREAD

**Issue by DaveARG** [toolcool-org/toolcool-range-slider#1] opened 2022-08-29 19:35 UTC
The event OnChange is trigger everything, for example:
1. $('#tool_range').val(2);
2. document.ready
3. when created toolcool-range inserting html whit input toolcool

**Comment by toolcool-org** [comment] 2022-08-29 19:40
I'm not sure I understand the issue. Could you please make an example illustrating the problem? For example, here - https://codepen.io/

**Comment by toolcool-org** [comment] 2022-09-08 21:11
Closing because there was no further response.

**Closed by toolcool-org** 2022-09-08 21:11 UTC

**Comment by galaxyblur** [comment] 2023-02-26 02:17
I think I might be experiencing the same thing. (I am using Vue2 and Nuxt, fwiw.)

When my parent component is mounted by Vue, I get a whole bunch of change events from tc-range-slider. I would expect the change event to only fire when a change happens after the initial value is set.

In my case, I'm getting 9 events -- 3 with the same value, 3 times each. I haven't opened an issue yet because I'm not sure what is happening exactly. If I can track it down, I'll let you know.

Thanks for the great component -- exactly what I was looking for (in particular, a horizontal and vertical slider). Good docs and good set of options!

**Comment by silvester-pari** [comment] 2023-08-16 10:42
Same here, it would be great to distinguish between user input and initial value. Currently the change event triggers in any occasion.

**Comment by mzusin** [comment] 2023-08-16 11:08
I created a simple demo in codepen with a 'change' event listener on page load:
https://codepen.io/1rosehip/pen/dywbROe?editors=1111

It seems that there are no events on page load in this scenario. 
Can you share a minimal reproducible example with your flow?

**Comment by gunhaxxor** [comment] 2023-10-12 12:16
Also had issue with change event getting triggered in conjunction/soon after page load.
I am using vue 3 composition api.
I hacked around the issue by attaching to the change event inside the onMounted lifecycle hook/callback. Something like this:
```typescript
...
const slider = ref<HTMLElement>();
onMounted(() => {
  slider.value?.addEventListener('change', (evt) => onChange(evt as CustomEvent));
});

....

```
